### ISSUE TITLE
Section describing how to compare two ECTs needed

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#283] opened 2024-09-18 23:00 UTC
Section 8.6.4 Processing a stateful environment against the Appraisal Claim Set should be moved / integrated into Section 8.9 ECT Comparison. 

Section 8.5 Reference Values Corroboration and Augmentation and section 8.6.1 language uses the word "match" to refer to condition ECT and ACS ECT matching semantics. When this issue is addressed, these sections should cross-reference section 8.9. 

Section 8.9 also describes ACS addition semantics.

**Comment by deeglaze** [comment] 2024-09-20 16:31
This is a duplicate of https://github.com/ietf-rats-wg/draft-ietf-rats-corim/issues/279 no?

**Comment by nedmsmith** [comment] 2024-10-02 22:44
Can this issue be closed now that PR #289 has been merged?

**Comment by deeglaze** [comment] 2024-10-02 23:47
Sounds good to me.

**Closed by deeglaze** 2024-10-02 23:47 UTC
